spring:
  application:
    name: gta-api
  jpa:
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gtadb		
  datasource:
    url: jdbc:postgresql://localhost:5432/gtadb
    username: postgres
    password: CYSE1972
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  
server:
  address: 129.174.95.42
  port: 8080


app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret:  ${jwt.secret} 
    expiration:
      ms: 86400000
      minutes: 10
    refreshExpiration:
      ms: 86400000

  cors:
    allowed-origins: http://localhost, http://129.174.95.42

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
